### ISSUE TITLE
judul

### ISSUE THREAD

**Issue by GilbertSitungkir09** [reacto11mecha/jadwal#1]
cara ganti judul 'jadwal pelajaran kls 10 bahasa' nya gimana bro

**Comment by reacto11mecha** [comment]
https://github.com/reacto11mecha/jadwal/blob/bc78ac8b5cbb9f97ed1fa1f61cb6e683ef66f824/src/Components/Table.jsx#L7

Ubah yang ini, soalnya ini make solid js. 11 12 nya sama react

**Comment by GilbertSitungkir09** [comment]
kok gw gk ada file 'Table.jsx' nya bro

**Comment by GilbertSitungkir09** [comment]
oke bro udh ketemu..

di hp file itu gk ada tpi gw coba di pc udh keliatan

ty yah

**Comment by reacto11mecha** [comment]
Iya sama sama, ku close ya
