### ISSUE TITLE
link

### ISSUE THREAD

**Issue by GilbertSitungkir09** [reacto11mecha/jadwal#2]
bro cara ganti link nya nanti gimana..

mksd gw link nya itu untuk yg di website biar keliatan jadwal nya

**Comment by reacto11mecha** [comment]
Deploy aja di vercel hasil fork mu, dengan catatan yang udah kamu ubah di local di push

**Comment by reacto11mecha** [comment]
https://vitejs.dev/guide/static-deploy.html#vercel

**Comment by reacto11mecha** [comment]
Atau nggak github pages kek juga bisa

**Comment by GilbertSitungkir09** [comment]
bgi no wa nya bro

**Comment by reacto11mecha** [comment]
Jangan wa, telegram aja

https://t.me/reacto_mecha

**Comment by reacto11mecha** [comment]
Ku close karena ga ada aktivitas lagi
